name: Build LaTeX Document

on: push

jobs:
  build:
    name: Build Document
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        name: Checkout Git repository
        uses: actions/checkout@v6

      - id: compile
        name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: BertrandBoyer.tex
          latexmk_use_lualatex: true
